language: ruby
dist: trusty
rvm:
  - 2.4.0
  - 2.5.0
  - ruby-head
  - jruby-9.2.0.0
jdk:
  - openjdk8
  - openjdk9
  - oraclejdk8
  - oraclejdk9

matrix:
  exclude:
    - rvm: 2.4.0
      jdk: openjdk8
    - rvm: 2.4.0
      jdk: openjdk9
    - rvm: 2.4.0
      jdk: oraclejdk8

    - rvm: 2.5.0
      jdk: openjdk8
    - rvm: 2.5.0
      jdk: openjdk9
    - rvm: 2.5.0
      jdk: oraclejdk8

    - rvm: ruby-head
      jdk: openjdk8
    - rvm: ruby-head
      jdk: openjdk9
    - rvm: ruby-head
      jdk: oraclejdk8

  allow_failures:
    - rvm: jruby-9.2.0.0
    - jdk:
      - oraclejdk9
      - openjdk9

branches:
  only:
    - master # Build only mster branch and pull requests
env:
  global:
    - CC_TEST_REPORTER_ID: 37cfc6aea5083afd5330559092fb31b953797474169652ce3093fe1c64b5bfab
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
